### ISSUE TITLE
May be mistake in codes

### ISSUE THREAD

**Issue by Nicholas10128** [Apress/ray-tracing-gems#1]
I found that in the source file which addressed at ray-tracing-gems/Ch_11_Automatic_Handling_of_Materials_in_Nested_Volumes/push.cpp may have a mistake. The index variable used at line 14 as prev_same is an index of the stack, not an index of the scene materials. So, I think the variable prev_same should be change to stack[prev_same].material_idx.Just like the following codes:

line 14 `if (material[material_idx] == material[prev_same]) {` => `if (material[material_idx] == material[stack[prev_same].material_idx]) {`

It was also used at line 26 but in right form:
line 26 `if ((material[stack[idx].material_idx] != material[material_idx]) &&`

**Comment by erich666** [comment]
Good catch, thanks! Fix confirmed by Matthias Raab and checked in with [this commit](https://github.com/Apress/ray-tracing-gems/commit/0ea976684cab6a986f7f73a88cc0bc2d4e87b2fe).
