### ISSUE TITLE
Source missing?

### ISSUE THREAD

**Issue by no-materials** [Apress/ray-tracing-gems#3]
Greetings I am interested in the implementation of Ch. 14 (Ch_14_Ray-Guided_Volumetric_Water_Caustics_in_Single_Scattering_Media_with_DXR), but it seems that the source code is missing. I can only find dll, exe & media files.

**Comment by erich666** [comment]
I believe the source was not released, just the demo. I have contacted the author to see if there is more that can be provided.

**Comment by erich666** [comment]
Checking around, there is nothing public yet, but I'm hoping this will change in the fairly near future. No promises, but stay tuned.

**Comment by no-materials** [comment]
I see, thanks for the quick response. Hopefully the author can provide more.

**Comment by erich666** [comment]
The code is now available at https://github.com/NvRTX/UnrealEngine/tree/NvRTX_Caustics

There is a warning that this branch is experimental due to compatibility issues.

**Comment by pierremoreau** [comment]
I am getting a 404 when trying to view that repository; has it been made public, or maybe it has not gone live yet?

**Comment by erich666** [comment]
Ah, interesting - I guess I have clearance, perhaps as an NVIDIA employee. Checking into it.

**Comment by erich666** [comment]
Got a response: You need to get your github account UE4 permissions first, from Epic: https://www.unrealengine.com/en-US/ue4-on-github

**Comment by pierremoreau** [comment]
Ah I see, thanks!
